### ISSUE TITLE
Suggestion when it comes to farming.

### ISSUE THREAD

**Issue by Punchie15** [Tantillus-BITMC/ReimannMC-Minecraft-server#2]
In many SkyBlock servers I have played on, farming is a big factor when it comes to money-making VIA the economy, and I feel like it should also be one of the main factors on this server when it comes to earning money. I am just addressing this suggestion as _1) There is no way to sell wheat. 2) The sell price of Potato and Carrot are only $0.1. 3) The sell price for Nether Wart is only $2._ I just feel like there should be that factor of making money rather than just getting a lot of spawners and making your money off just gems. Hopefully you take my suggestion into consideration 😄

**Comment by Tantillus-KW1C** [comment]
Hey Punchie, thanks for your suggestions.

The remake of the entire economy was already on the [_**project board**_](https://github.com/ReimannMC/ReimannMC-Minecraft-server/projects/1) but never the less we appreciate your idea's that affect the players that just joined. I'll add this to the _**[project board](https://github.com/ReimannMC/ReimannMC-Minecraft-server/projects/1)**_, so that it **will** be looked into.  

If you have any questions or other idea's/problems, be sure to create another ticket.

~ Tantillus
    Developer
