### ISSUE TITLE
Server Suggestions for the future.

### ISSUE THREAD

**Issue by Punchie15** [Tantillus-BITMC/ReimannMC-Minecraft-server#5]
I feel like once SkyBlock is 100% set up, the server should expand out in different directions. In order for the server to reach its full potential and to gain extra members that are active and will play the server, I feel like adding different servers like Factions, Prison, and maybe a minigames server. I know that it could be copying other servers but we could make twists to the server by adding our own custom things. Also I know money is a factor in all of this, so if you would like to agree with my suggestion above with expanding the server creating different games, I would highly suggest making the donator ranks just a small bit more expensive, as of right now they are undoubtedly cheap, and you will need that extra couple $ if you would like to go on with my server suggestion. As always, I would love to be apart of the building of this server and would like to participate into making this server a big and active server. Hopefully you take my suggestion to great consideration! :)

**Comment by Tantillus-KW1C** [comment]
This ticket received a "wontfix" status.

Not because your suggestion is being rejected, as a matter in fact **it's a great ticket which we will look into.** Nevertheless, this ticket received this particular tag because for the time being we're not ready to even think about looking at different game modes. 

@Punchie15 said:

> "I feel like once SkyBlock is 100% set up, the server should expand out in different directions."

Once the Skyblock server is operating 90% to our liking, and has a uptime of over 95% we will start shifting our dedication to other game modes as well. Until then, logically, our priority is on the Skyblock server.

This ticket will be revisited once we've reached the point where we're going to start looking into different gamemodes.

Thanks Punchie 👍 

~Tantillus
   Server Development
