### ISSUE TITLE
Leveling up system.

### ISSUE THREAD

**Issue by Punchie15** [Tantillus-BITMC/ReimannMC-Minecraft-server#6]
Just a tiny idea, to add a leveling up system that is used by player time, and every time you level up you get X amount of money or tokens or something. Lets say tokens, you can then use those tokens to buy stuff at a tokenshop that could be set up. I think it would be good, just to see how much time people actually dedicate to playing on the server rather than just afk-ing or not playing at all.

**Comment by Tantillus-KW1C** [comment]
Thanks for your suggestion Punchie.

Though, because we allow being AFK on the server, there is no way knowning the true active playtime of any player. This is until we can find a plugin that actually knows the difference between when one is AFK and when he/she isn't. We've tried many, but none of them worked to our satisfaction.

Therefore, your suggestion won't be worked on as it just wouldn't be as reliable as we would like.

Thanks Punch,

~ Tantillus
